### ISSUE TITLE
MissingSchema issue

### ISSUE THREAD

**Issue by XueyangLiOSU** [andreped/livermask#15] opened 2022-10-20 09:06 UTC
Traceback (most recent call last):
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 116, in <module>
    main()
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 112, in main
    func(*vars(ret).values())
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 40, in func
    get_model(name)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\utils\utils.py", line 10, in get_model
    gdown.cached_download(url, output, md5=md5) #, postprocess=gdown.extractall)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\gdown\cached_download.py", line 123, in cached_download
    download(url, temp_path, quiet=quiet, proxy=proxy, speed=speed)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\gdown\download.py", line 114, in download
    res = sess.get(url, headers=headers, stream=True)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

Did anyone have the same issue as me?

**Comment by XueyangLiOSU** [comment] 2022-10-20 09:10
Traceback (most recent call last):
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 116, in <module>
    main()
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 112, in main
    func(*vars(ret).values())
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\livermask.py", line 40, in func
    get_model(name)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\livermask\utils\utils.py", line 10, in get_model
    gdown.cached_download(url, output, md5=md5) #, postprocess=gdown.extractall)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\gdown\cached_download.py", line 123, in cached_download
    download(url, temp_path, quiet=quiet, proxy=proxy, speed=speed)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\gdown\download.py", line 114, in download
    res = sess.get(url, headers=headers, stream=True)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Cyanb\anaconda3\envs\spade\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

**Comment by sunnyisabaster** [comment] 2022-10-27 02:03
Same issue, have u sovled?

**Comment by andreped** [comment] 2022-10-27 07:43
Hello @XueyangLiOSU and @sunnyisabaster,

for each commit I am running some checks to assess whether livermask can be installed in a conda environment. See here:
https://github.com/andreped/livermask/actions/runs/2989356935/jobs/4793011384

However, I have not ran the same checks on Windows, only Ubunt u 20.04. See workflow file:
https://github.com/andreped/livermask/blob/master/.github/workflows/build.yml#L71

Can you give me more information on the local setups you have? Which operating system, which python version, which conda version, how did you try to install livermask (through pip or conda).

From the first comment, it seems like it installs successfully but fails during usage. Is that true?

**Comment by andreped** [comment] 2022-10-27 07:44
Hmm, from the print above it also seems like the download from google drive fails. Might be that the model was deleted from the drive, for whatever reason. I will check this now.

**Comment by andreped** [comment] 2022-10-27 08:31
From what I can find, this issue seems to be related to gdown:
https://github.com/wkentaro/gdown/issues/112

Basically, they say here that the error message being prompted is wrong, but you are actually having permission issues, which in turn seems to be related to this:
https://github.com/wkentaro/gdown/issues/43#issuecomment-642182100

and
https://github.com/wkentaro/gdown/issues/43#issuecomment-1209073734

Seems to be that if there has been a lot of downloads recently, that you are disallowed download, which is silly. It is an open issue at gdown.

I will try to upgrade gdown to the latest version (given that it works with the CI tests), and you can try again.

**Comment by andreped** [comment] 2022-11-28 09:34
As I have not heard anything, I'm closing this issue for now. If anyone experience the same issue, please, reopen and we can make a new iteration.

**Comment by andreped** [comment] 2022-12-16 16:59
Just reproduced this when trying to use livermask in a separate project on macOS. I will try to find a workaround.

**Comment by andreped** [comment] 2022-12-16 17:15
The more I look into the issue, I find that the vessel model works perfectly with gdown, but it fails for the parenchyma model. The latter model is much larger, and when trying to download through the browser you get prompted that "the file is too large to check for viruses". In the browser you are still able to download by clicking a button, but for the CLI gdown, this is not possible, as discussed in this issue:
https://github.com/wkentaro/gdown/issues/26

Hence, 1) we make a smaller parenchyma model or 2) we use a separate solution, which likely also means that we will have to use a different solution than gdown.

**Comment by andreped** [comment] 2022-12-16 20:18
I managed to fix the problem by switching the gdown solution with a custom HTTP + GitHub Releases approach, which at least seems to work in the CIs and the test machine where I observed the issue.

@XueyangLiOSU & @sunnyisabaster if you have time, it would be great if you could test the latest release and let me know if it works for you. Simply install by:
```
pip install https://github.com/andreped/livermask/releases/download/v1.4.0/livermask-1.4.0-py3-none-any.whl
```

**Comment by andreped** [comment] 2023-01-10 12:39
Haven't heard anything, so I am assuming everything is working. Hence, closing this issue now. If anyone observe the same issue in the future, make a comment here and I will reopen the issue.

**Closed by andreped** 2023-01-10 12:39 UTC
Labels: bug
